Feat/honeycomb harvest all
1Hive/tulip-frontend pull request #109
Opened 2021-07-01 04:03 UTC by jupiteruwdev

2021-07-01 12:13 UTC, MrClottom commented on src/components/Farming/DepositTable/index.js
> +import HarvestAll from '../HavestAll'
Spelling error

2021-07-01 12:14 UTC, MrClottom commented on src/components/Farming/DepositTable/index.js
> +    items.forEach(
please opt to using a `.reduce()` pattern.

2021-07-01 12:16 UTC, MrClottom commented on src/components/Farming/HavestAll/index.js
> +  const handleHarvestAll = () => {
Please use async / await

2021-07-02 14:30 UTC, pxbee requested changes

2021-07-02 14:30 UTC, pxbee commented on src/components/Farming/DepositTable/index.js
> +    const rewardBalanceSum = items.reduce(
Please use truncateDecimals on dollar amount and sum as well

2021-07-02 15:06 UTC, pxbee requested changes
Please merge latest master deployment to get the correct addresses in the network.js

2021-07-02 15:06 UTC, pxbee commented on src/networks.js
> +    multiWithdrawer: '0x53f224f83b2b2365caf4178f52c234da1ecf392f',
Please add multiwithdrawer for polygon as well. You can find the address here https://github.com/1Hive/honeyswap-farm/blob/polygon-airdrop/addresses.json

2021-07-02 20:22 UTC, merged